
package ar.gov.rosario.gait.apsv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Apsv", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Apsv {


    /**
     * 
     * @param obtenerInhabilitacionRequest
     * @return
     *     returns ar.gov.rosario.gait.apsv.ObtenerInhabilitacionResponse
     */
    @WebMethod
    @WebResult(name = "obtenerInhabilitacionResponse", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "obtenerInhabilitacionResponse")
    public ObtenerInhabilitacionResponse obtenerInhabilitacion(
        @WebParam(name = "obtenerInhabilitacionRequest", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "obtenerInhabilitacionRequest")
        ObtenerInhabilitacionRequest obtenerInhabilitacionRequest);

    /**
     * 
     * @param obtenerLicenciaRequest
     * @return
     *     returns ar.gov.rosario.gait.apsv.ObtenerLicenciaResponse
     */
    @WebMethod
    @WebResult(name = "obtenerLicenciaResponse", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "obtenerLicenciaResponse")
    public ObtenerLicenciaResponse obtenerLicencia(
        @WebParam(name = "obtenerLicenciaRequest", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "obtenerLicenciaRequest")
        ObtenerLicenciaRequest obtenerLicenciaRequest);

    /**
     * 
     * @param obtenerNoAptitudRequest
     * @return
     *     returns ar.gov.rosario.gait.apsv.ObtenerNoAptitudResponse
     */
    @WebMethod
    @WebResult(name = "obtenerNoAptitudResponse", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "obtenerNoAptitudResponse")
    public ObtenerNoAptitudResponse obtenerNoAptitud(
        @WebParam(name = "obtenerNoAptitudRequest", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "obtenerNoAptitudRequest")
        ObtenerNoAptitudRequest obtenerNoAptitudRequest);

    /**
     * 
     * @param obtenerPersonaRequest
     * @return
     *     returns ar.gov.rosario.gait.apsv.ObtenerPersonaResponse
     */
    @WebMethod
    @WebResult(name = "obtenerPersonaResponse", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "obtenerPersonaResponse")
    public ObtenerPersonaResponse obtenerPersona(
        @WebParam(name = "obtenerPersonaRequest", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "obtenerPersonaRequest")
        ObtenerPersonaRequest obtenerPersonaRequest);

    /**
     * 
     * @param testRequest
     * @return
     *     returns ar.gov.rosario.gait.apsv.TestResponse
     */
    @WebMethod
    @WebResult(name = "testResponse", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "testResponse")
    public TestResponse test(
        @WebParam(name = "testRequest", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", partName = "testRequest")
        TestRequest testRequest);

}
