
package ar.gov.rosario.gait.apsv;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ApsvService", targetNamespace = "http://www.rosario.gov.ar/Apsv/schema", wsdlLocation = "file:/home/cristian.taibbi/workspaces/gait/server/readme/apsv.wsdl")
public class ApsvService
    extends Service
{

    private final static URL APSVSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ar.gov.rosario.gait.apsv.ApsvService.class.getName());
    private final static QName APSVSERVICE_QNAME = new QName("http://www.rosario.gov.ar/Apsv/schema", "ApsvService");

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ar.gov.rosario.gait.apsv.ApsvService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/cristian.taibbi/workspaces/gait/server/readme/apsv.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/cristian.taibbi/workspaces/gait/server/readme/apsv.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APSVSERVICE_WSDL_LOCATION = url;
    }
    
    public ApsvService() {
    	super(APSVSERVICE_WSDL_LOCATION, APSVSERVICE_QNAME);
    }

    public ApsvService(URL wsdlLocation) {
        super(wsdlLocation, APSVSERVICE_QNAME);
    }
    
    public ApsvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    /**
     * 
     * @return
     *     returns Apsv
     */
    @WebEndpoint(name = "ApsvSoap11")
    public Apsv getApsvSoap11() {
        return super.getPort(new QName("http://www.rosario.gov.ar/Apsv/schema", "ApsvSoap11"), Apsv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Apsv
     */
    @WebEndpoint(name = "ApsvSoap11")
    public Apsv getApsvSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.rosario.gov.ar/Apsv/schema", "ApsvSoap11"), Apsv.class, features);
    }

}
