
package ar.gov.rosario.gait.simgei.auth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthenticationWebServiceBeanService", targetNamespace = "http://ws.admusu.santafeciudad.gov.ar/", wsdlLocation = "http://10.20.12.26:8080/simgeiWS/AuthenticationWebServiceBean?wsdl")
public class AuthenticationWebServiceBeanService
    extends Service
{

    private final static URL AUTHENTICATIONWEBSERVICEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATIONWEBSERVICEBEANSERVICE_EXCEPTION;
    private final static QName AUTHENTICATIONWEBSERVICEBEANSERVICE_QNAME = new QName("http://ws.admusu.santafeciudad.gov.ar/", "AuthenticationWebServiceBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.20.12.26:8080/simgeiWS/AuthenticationWebServiceBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATIONWEBSERVICEBEANSERVICE_WSDL_LOCATION = url;
        AUTHENTICATIONWEBSERVICEBEANSERVICE_EXCEPTION = e;
    }

    public AuthenticationWebServiceBeanService() {
        super(__getWsdlLocation(), AUTHENTICATIONWEBSERVICEBEANSERVICE_QNAME);
    }

    public AuthenticationWebServiceBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATIONWEBSERVICEBEANSERVICE_QNAME, features);
    }

    public AuthenticationWebServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATIONWEBSERVICEBEANSERVICE_QNAME);
    }

    public AuthenticationWebServiceBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATIONWEBSERVICEBEANSERVICE_QNAME, features);
    }

    public AuthenticationWebServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationWebServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticationWebService
     */
    @WebEndpoint(name = "AuthenticationWebServiceBeanPort")
    public AuthenticationWebService getAuthenticationWebServiceBeanPort() {
        return super.getPort(new QName("http://ws.admusu.santafeciudad.gov.ar/", "AuthenticationWebServiceBeanPort"), AuthenticationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationWebService
     */
    @WebEndpoint(name = "AuthenticationWebServiceBeanPort")
    public AuthenticationWebService getAuthenticationWebServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.admusu.santafeciudad.gov.ar/", "AuthenticationWebServiceBeanPort"), AuthenticationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATIONWEBSERVICEBEANSERVICE_EXCEPTION!= null) {
            throw AUTHENTICATIONWEBSERVICEBEANSERVICE_EXCEPTION;
        }
        return AUTHENTICATIONWEBSERVICEBEANSERVICE_WSDL_LOCATION;
    }

}
