/*******************************************************************************
 * Copyright (c) 2016 Municipalidad de Rosario, Coop. de Trabajo Tecso Ltda.
 *
 * This file is part of GAEM.
 *
 * GAEM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 *
 * GAEM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GAEM.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/

package ar.gov.rosario.gait.simgei.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsuarioWebServiceBeanService", targetNamespace = "http://ws.admusu.santafeciudad.gov.ar/", wsdlLocation = "http://simgei.santafeciudad.gov.ar:8080/simgeiWS/UsuarioWebServiceBean?wsdl")

public class UsuarioWebServiceBeanService
    extends Service
{

    private final static URL USUARIOWEBSERVICEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException USUARIOWEBSERVICEBEANSERVICE_EXCEPTION;
    private final static QName USUARIOWEBSERVICEBEANSERVICE_QNAME = new QName("http://ws.admusu.santafeciudad.gov.ar/", "UsuarioWebServiceBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://simgei.santafeciudad.gov.ar:8080/simgeiWS/UsuarioWebServiceBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOWEBSERVICEBEANSERVICE_WSDL_LOCATION = url;
        USUARIOWEBSERVICEBEANSERVICE_EXCEPTION = e;
    }

    public UsuarioWebServiceBeanService() {
        super(__getWsdlLocation(), USUARIOWEBSERVICEBEANSERVICE_QNAME);
    }

    public UsuarioWebServiceBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOWEBSERVICEBEANSERVICE_QNAME, features);
    }

    public UsuarioWebServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOWEBSERVICEBEANSERVICE_QNAME);
    }

    public UsuarioWebServiceBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOWEBSERVICEBEANSERVICE_QNAME, features);
    }

    public UsuarioWebServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioWebServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuarioWebService
     */
    @WebEndpoint(name = "UsuarioWebServiceBeanPort")
    public UsuarioWebService getUsuarioWebServiceBeanPort() {
        return super.getPort(new QName("http://ws.admusu.santafeciudad.gov.ar/", "UsuarioWebServiceBeanPort"), UsuarioWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioWebService
     */
    @WebEndpoint(name = "UsuarioWebServiceBeanPort")
    public UsuarioWebService getUsuarioWebServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.admusu.santafeciudad.gov.ar/", "UsuarioWebServiceBeanPort"), UsuarioWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOWEBSERVICEBEANSERVICE_EXCEPTION!= null) {
            throw USUARIOWEBSERVICEBEANSERVICE_EXCEPTION;
        }
        return USUARIOWEBSERVICEBEANSERVICE_WSDL_LOCATION;
    }

}
