/*******************************************************************************
 * Copyright (c) 2016 Municipalidad de Rosario, Coop. de Trabajo Tecso Ltda.
 *
 * This file is part of GAEM.
 *
 * GAEM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 *
 * GAEM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GAEM.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/

package ar.gov.rosario.gait.tmf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Tribunal", targetNamespace = "http://www.rosario.gov.ar/Tribunal/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Tribunal {


    /**
     * 
     * @param testRequest
     * @return
     *     returns ar.gov.rosario.gait.tmf.TestResponse
     */
    @WebMethod
    @WebResult(name = "testResponse", targetNamespace = "http://www.rosario.gov.ar/Tribunal/schema", partName = "testResponse")
    public TestResponse test(
        @WebParam(name = "testRequest", targetNamespace = "http://www.rosario.gov.ar/Tribunal/schema", partName = "testRequest")
        TestRequest testRequest);

    /**
     * 
     * @param obtenerInspectorPorLoginRequest
     * @return
     *     returns ar.gov.rosario.gait.tmf.ObtenerInspectorPorLoginResponse
     */
    @WebMethod
    @WebResult(name = "obtenerInspectorPorLoginResponse", targetNamespace = "http://www.rosario.gov.ar/Tribunal/schema", partName = "obtenerInspectorPorLoginResponse")
    public ObtenerInspectorPorLoginResponse obtenerInspectorPorLogin(
        @WebParam(name = "obtenerInspectorPorLoginRequest", targetNamespace = "http://www.rosario.gov.ar/Tribunal/schema", partName = "obtenerInspectorPorLoginRequest")
        ObtenerInspectorPorLoginRequest obtenerInspectorPorLoginRequest);

    /**
     * 
     * @param registrarActaTransitoRequest
     * @return
     *     returns ar.gov.rosario.gait.tmf.RegistrarActaTransitoResponse
     */
    @WebMethod
    @WebResult(name = "registrarActaTransitoResponse", targetNamespace = "http://www.rosario.gov.ar/Tribunal/schema", partName = "registrarActaTransitoResponse")
    public RegistrarActaTransitoResponse registrarActaTransito(
        @WebParam(name = "registrarActaTransitoRequest", targetNamespace = "http://www.rosario.gov.ar/Tribunal/schema", partName = "registrarActaTransitoRequest")
        RegistrarActaTransitoRequest registrarActaTransitoRequest);

}
