/*******************************************************************************
 * Copyright (c) 2016 Municipalidad de Rosario, Coop. de Trabajo Tecso Ltda.
 *
 * This file is part of GAEM.
 *
 * GAEM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 *
 * GAEM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GAEM.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/

package ar.gov.rosario.gait.tmf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TribunalService", targetNamespace = "http://www.rosario.gov.ar/Tribunal/schema", wsdlLocation = "file:/home/cristian.taibbi/workspaces/gait/server/readme/tribunal.wsdl")
public class TribunalService
    extends Service
{

    private final static URL TRIBUNALSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRIBUNALSERVICE_EXCEPTION;
    private final static QName TRIBUNALSERVICE_QNAME = new QName("http://www.rosario.gov.ar/Tribunal/schema", "TribunalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/cristian.taibbi/workspaces/gait/server/readme/tribunal.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRIBUNALSERVICE_WSDL_LOCATION = url;
        TRIBUNALSERVICE_EXCEPTION = e;
    }

    public TribunalService() {
        super(__getWsdlLocation(), TRIBUNALSERVICE_QNAME);
    }

    public TribunalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRIBUNALSERVICE_QNAME, features);
    }

    public TribunalService(URL wsdlLocation) {
        super(wsdlLocation, TRIBUNALSERVICE_QNAME);
    }

    public TribunalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRIBUNALSERVICE_QNAME, features);
    }

    public TribunalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TribunalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Tribunal
     */
    @WebEndpoint(name = "TribunalSoap11")
    public Tribunal getTribunalSoap11() {
        return super.getPort(new QName("http://www.rosario.gov.ar/Tribunal/schema", "TribunalSoap11"), Tribunal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tribunal
     */
    @WebEndpoint(name = "TribunalSoap11")
    public Tribunal getTribunalSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.rosario.gov.ar/Tribunal/schema", "TribunalSoap11"), Tribunal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRIBUNALSERVICE_EXCEPTION!= null) {
            throw TRIBUNALSERVICE_EXCEPTION;
        }
        return TRIBUNALSERVICE_WSDL_LOCATION;
    }

}
